{"service":"user-service","level":"error","message":"test test","stack":"Error: test\n    at C:\\dev\\Node_js\\finferie\\routes\\users.js:8:11\n    at newFn (C:\\dev\\Node_js\\finferie\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\dev\\Node_js\\finferie\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\dev\\Node_js\\finferie\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\dev\\Node_js\\finferie\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\dev\\Node_js\\finferie\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\dev\\Node_js\\finferie\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\dev\\Node_js\\finferie\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\dev\\Node_js\\finferie\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\dev\\Node_js\\finferie\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\dev\\Node_js\\finferie\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\dev\\Node_js\\finferie\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at newFn (C:\\dev\\Node_js\\finferie\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\dev\\Node_js\\finferie\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\dev\\Node_js\\finferie\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at C:\\dev\\Node_js\\finferie\\node_modules\\express\\lib\\router\\index.js:284:7"}
{"service":"user-service","level":"error","message":"It appears you have done something like `app.use(helmet)`, but it should be `app.use(helmet())`. It appears you have done something like `app.use(helmet)`, but it should be `app.use(helmet())`.","stack":"Error: It appears you have done something like `app.use(helmet)`, but it should be `app.use(helmet())`.\n    at helmet (C:\\dev\\Node_js\\finferie\\node_modules\\helmet\\dist\\index.js:23:10)\n    at newFn (C:\\dev\\Node_js\\finferie\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\dev\\Node_js\\finferie\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\dev\\Node_js\\finferie\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at C:\\dev\\Node_js\\finferie\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (C:\\dev\\Node_js\\finferie\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\dev\\Node_js\\finferie\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at C:\\dev\\Node_js\\finferie\\node_modules\\body-parser\\lib\\read.js:130:5\n    at invokeCallback (C:\\dev\\Node_js\\finferie\\node_modules\\raw-body\\index.js:224:16)\n    at done (C:\\dev\\Node_js\\finferie\\node_modules\\raw-body\\index.js:213:7)\n    at IncomingMessage.onEnd (C:\\dev\\Node_js\\finferie\\node_modules\\raw-body\\index.js:273:7)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (_stream_readable.js:1220:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"}
{"service":"user-service","expose":true,"statusCode":400,"status":400,"body":"{\r\n    \"name\" : \"maibritt\",\r\n    \"password\" : \"q2w3e4r5\"\r\n    \"phone\" : \"51966991\",\r\n    \"email\" : \"mri@skivecollege.dk\",\r\n    \"address\" : \"Højmarksvej 31\",\r\n    \"zip\" : \"7840\",    \r\n    \"city\" : \"Højslev\",\r\n    \"isAdmin\" : true\r\n}","type":"entity.parse.failed","level":"error","message":"Unexpected string in JSON at position 62 Unexpected string in JSON at position 62","stack":"SyntaxError: Unexpected string in JSON at position 62\n    at JSON.parse (<anonymous>)\n    at parse (C:\\dev\\Node_js\\finferie\\node_modules\\body-parser\\lib\\types\\json.js:89:19)\n    at C:\\dev\\Node_js\\finferie\\node_modules\\body-parser\\lib\\read.js:121:18\n    at invokeCallback (C:\\dev\\Node_js\\finferie\\node_modules\\raw-body\\index.js:224:16)\n    at done (C:\\dev\\Node_js\\finferie\\node_modules\\raw-body\\index.js:213:7)\n    at IncomingMessage.onEnd (C:\\dev\\Node_js\\finferie\\node_modules\\raw-body\\index.js:273:7)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (_stream_readable.js:1220:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"}
{"service":"user-service","level":"error","message":"Operation `users.findOne()` buffering timed out after 10000ms Operation `users.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\dev\\Node_js\\finferie\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:184:20)\n    at listOnTimeout (internal/timers.js:549:17)\n    at processTimers (internal/timers.js:492:7)"}
{"service":"user-service","level":"error","message":"Operation `users.findOne()` buffering timed out after 10000ms Operation `users.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\dev\\Node_js\\finferie\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:184:20)\n    at listOnTimeout (internal/timers.js:549:17)\n    at processTimers (internal/timers.js:492:7)"}
{"service":"user-service","level":"error","message":"Operation `users.findOne()` buffering timed out after 10000ms Operation `users.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\dev\\Node_js\\finferie\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:184:20)\n    at listOnTimeout (internal/timers.js:549:17)\n    at processTimers (internal/timers.js:492:7)"}
{"service":"user-service","level":"error","message":"Operation `users.findOne()` buffering timed out after 10000ms Operation `users.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\dev\\Node_js\\finferie\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:184:20)\n    at listOnTimeout (internal/timers.js:549:17)\n    at processTimers (internal/timers.js:492:7)"}
{"service":"user-service","stringValue":"\"1\"","kind":"ObjectId","value":"1","path":"_id","reason":{},"level":"error","message":"Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"Users\" Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"Users\"","stack":"CastError: Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"Users\"\n    at model.Query.exec (C:\\dev\\Node_js\\finferie\\node_modules\\mongoose\\lib\\query.js:4358:21)\n    at model.Query.Object.<anonymous>.Query.then (C:\\dev\\Node_js\\finferie\\node_modules\\mongoose\\lib\\query.js:4450:15)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
{"service":"user-service","stringValue":"\"1\"","kind":"ObjectId","value":"1","path":"_id","reason":{},"level":"error","message":"Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"Users\" Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"Users\"","stack":"CastError: Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"Users\"\n    at model.Query.exec (C:\\dev\\Node_js\\finferie\\node_modules\\mongoose\\lib\\query.js:4358:21)\n    at model.Query.Object.<anonymous>.Query.then (C:\\dev\\Node_js\\finferie\\node_modules\\mongoose\\lib\\query.js:4450:15)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
{"service":"user-service","stringValue":"\"1\"","kind":"ObjectId","value":"1","path":"_id","reason":{},"level":"error","message":"Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"Users\" Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"Users\"","stack":"CastError: Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"Users\"\n    at model.Query.exec (C:\\dev\\Node_js\\finferie\\node_modules\\mongoose\\lib\\query.js:4358:21)\n    at model.Query.Object.<anonymous>.Query.then (C:\\dev\\Node_js\\finferie\\node_modules\\mongoose\\lib\\query.js:4450:15)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
{"service":"user-service","stringValue":"\"1\"","kind":"ObjectId","value":"1","path":"_id","reason":{},"level":"error","message":"Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"Users\" Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"Users\"","stack":"CastError: Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"Users\"\n    at model.Query.exec (C:\\dev\\Node_js\\finferie\\node_modules\\mongoose\\lib\\query.js:4358:21)\n    at model.Query.Object.<anonymous>.Query.then (C:\\dev\\Node_js\\finferie\\node_modules\\mongoose\\lib\\query.js:4450:15)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
{"service":"user-service","stringValue":"\"1\"","kind":"ObjectId","value":"1","path":"_id","reason":{},"level":"error","message":"Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"Users\" Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"Users\"","stack":"CastError: Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"Users\"\n    at model.Query.exec (C:\\dev\\Node_js\\finferie\\node_modules\\mongoose\\lib\\query.js:4358:21)\n    at model.Query.Object.<anonymous>.Query.then (C:\\dev\\Node_js\\finferie\\node_modules\\mongoose\\lib\\query.js:4450:15)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
